# Generated by Django 5.1.1 on 2024-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=121)),
                ('s_roll', models.IntegerField(unique=True)),
                ('s_address', models.CharField(max_length=212)),
                ('city', models.CharField(max_length=121)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
